name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码 
      - name: Checkout              # name表示action的名称
        uses: actions/checkout@v2   # uses表示别人写好的插件
        with:                       # 传给插件的参数
          persist-credentials: false
    
      # 1、生成静态文件
      - name: Build
        run: npm install && npm run build
      
      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:              
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}            # 本仓库的环境变量，配置在仓库设置里面的 secrets 菜单栏
          REPOSITORY_NAME: guangmujun/guangmujun.github.io
          BRANCH: master
          FOLDER: public
          # 注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`


